version: "3"
services:
  joplin:
    # build:
    #   context: .
    #   args:
    #     NODE_VERSION: 14.15.5
    #     JOPLIN_VERSION: 1.6.4
    image: jspiers/headless-joplin:1.6.4-node-14.15.5
    volumes:
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    ports:
      - "3000:80"
    command: ["joplin", "server", "start"]
    secrets:
      - joplin-config.json
volumes:
  joplin-data:
secrets:
  joplin-config.json:
    file: ./joplin-config.json
